version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MONGODB_URL=${MONGODB_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - PLAYLIST_ID=${PLAYLIST_ID}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
      - PREVIEW_URL=${PREVIEW_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 