[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"
rootDirectory = "."
engines = { python = "3.11" }

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100 